cors:
  originPattenrs: http://localhost:3000,http://localhost:8080
spring:
  datasource:
    url: jdbc:h2:mem:management_person;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show-sql: true
        format-sql: true
springdoc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true
  default-consumes-media-type: application/json
  auto-tag-classes: true